import datetime
import os.path
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import config

SCOPES = ['https://www.googleapis.com/auth/documents']

def get_docs_service():
    """
    Returns an authenticated Google Docs service.
    """
    if os.path.exists(config.SERVICE_ACCOUNT_FILE):
        creds = service_account.Credentials.from_service_account_file(
            config.SERVICE_ACCOUNT_FILE, scopes=SCOPES)
        return build('docs', 'v1', credentials=creds)
    else:
        print("Service account file not found.")
        return None

def append_text_to_doc(doc_id, text):
    """
    Appends the given text to the end of the Google Doc.
    """
    service = get_docs_service()
    if not service:
        return False

    try:
        # Get current document length to append at the end
        doc = service.documents().get(documentId=doc_id).execute()
        content = doc.get('body').get('content')
        end_index = content[-1].get('endIndex') - 1

        requests = [
            {
                'insertText': {
                    'location': {
                        'index': end_index
                    },
                    'text': text + "\n"
                }
            }
        ]

        result = service.documents().batchUpdate(
            documentId=doc_id, body={'requests': requests}).execute()
        print(f"Appended text to Doc: {doc_id}")
        return True
    except HttpError as err:
        print(f"Google Docs API Error: {err}")
        return False

def append_daily_summary(doc_id, summary_text, date_str=None):
    """
    Appends a formatted daily summary to the Google Doc.
    summary_text is expected to be the content generated by the AI.
    """
    if not date_str:
        date_str = datetime.datetime.now().strftime("%Y/%m/%d")

    header = f"\n\n========================================\n【{date_str} のまとめ】\n========================================\n"
    
    full_content = header + summary_text + "\n"
    
    return append_text_to_doc(doc_id, full_content)
